style: 無意味なダブルクオートをシングルクオートに原則統一
シングルクオートの中か、
変数やコマンド展開を使っていると印象づけたい。

diff --git a/bin/dwim-open b/bin/dwim-open
--- a/bin/dwim-open
+++ b/bin/dwim-open
@@ -9,5 +9,5 @@ elif hash xdg-open 2>/dev/null; then
   exec xdg-open "$@"
 fi
 
-echo "open like command is not found" >&2
+echo 'open like command is not found' >&2
 exit 1
